apiVersion: v1
kind: Service
metadata:
  name: client_api
  labels:
    app: client_api-service
spec:
  selector:
    app: client_api-pod
  ports:
    - protocol: TCP
      port: 8000
      name: http
      targetPort: 8000
  type: ClusterIP
