apiVersion: apps/v1
kind: Deployment
metadata:
  name: client_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client_api-pod
  template:
    metadata:
      labels:
        app: client_api-pod
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 80
              name: http
          image: "client_api"
          imagePullPolicy: IfNotPresent # Necessary for Kubernetes via Docker Desktop
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: TRITON_SERVICE
              value: tritonserver.default.svc.cluster.local:8000
