apiVersion: apps/v1
kind: Deployment
metadata:
  name: tritonserver
  labels:
    app: tritonserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tritonserver-pod
  template:
    metadata:
      labels:
        app: tritonserver-pod
    spec:
      containers:
        - name: main
          ports:
            - containerPort: 8000
              name: http-triton
            - containerPort: 8001
              name: grpc-triton
            - containerPort: 8002
              name: metrics-triton
          image: "nvcr.io/nvidia/tritonserver:20.12-py3"
          resources:
            limits:
              nvidia.com/mig-1g.5gb: 1
              cpu: 1
              memory: 4Gi
