apiVersion: v1
kind: Service
metadata:
  name: tritonserver
  labels:
    app: tritonserver-service
spec:
  selector:
    app: tritonserver-deployment
  ports:
    - protocol: TCP
      port: 8000
      name: http
      targetPort: 8000
    - protocol: TCP
      port: 8001
      name: grpc
      targetPort: 8001
    - protocol: TCP
      port: 8002
      name: metrics
      targetPort: 8002
  type: ClusterIP
